jobs:
  check-upstream-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        run: |
          git init
          git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git
          git remote add upstream https://github.com/UPSTREAM_USERNAME/UPSTREAM_REPO.git

      - name: Check for updates in upstream
        run: |
          echo "Fetching updates from upstream..."
          git fetch upstream
          git log HEAD..upstream/main --oneline > updates.txt || echo ""
          if [ -s updates.txt ]; then
              echo "New updates found in the upstream repository."
              cat updates.txt
          else
              echo "No updates in the upstream repository."
              exit 0
          fi

      - name: Send email notification
        if: success() && steps.check-for-updates.outputs.UPDATES != ''
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          echo "Sending email notification..."
          python3 - <<EOF
          import smtplib
          from email.mime.text import MIMEText

          sender = "${{ secrets.EMAIL_SENDER }}"
          receiver = "${{ secrets.EMAIL_RECEIVER }}"
          password = "${{ secrets.EMAIL_PASSWORD }}"
          subject = "Updates Detected in Upstream Repository"

          with open('updates.txt', 'r') as f:
              updates = f.read()

          body = f"The following updates were detected in the upstream repository:\n\n{updates}"

          msg = MIMEText(body)
          msg['Subject'] = subject
          msg['From'] = sender
          msg['To'] = receiver

          try:
              with smtplib.SMTP("smtp.gmail.com", 587) as server:
                  server.starttls()
                  server.login(sender, password)
                  server.sendmail(sender, receiver, msg.as_string())
              print("Email sent successfully!")
          except Exception as e:
              print(f"Failed to send email: {e}")
          EOF
